#!/usr/bin/env ruby

require 'base64'

#
# USAGE:
#
# tobase64 blue.png
# cat blue.png.base64.txt
#

ARGV.each do |fname|

  next unless File.exist?(fname)

  #xname = File.extname(fname)[1..-1]
  type = `file -i #{fname}`.split(' ')[1]

  #b64 = Base64.urlsafe_encode64(File.read(fname)) # NO
  b64 = Base64.encode64(File.read(fname)).gsub(/\n/, '') # YES

  tname = "#{fname}.base64.txt"

  File.open(tname, 'wb') do |f|
    f.print("data:#{type};base64,")
    f.print(b64)
  end

  puts " . wrote #{tname}"
end

